# Generated by Django 2.2.1 on 2019-06-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
    ]
