# Generated by Django 2.2.1 on 2019-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190608_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='qr',
            field=models.CharField(default='Data/no_qr.png', max_length=30),
        ),
    ]
