# Generated by Django 2.2.1 on 2019-06-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_appuser_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='info',
            field=models.IntegerField(default=0),
        ),
    ]
