# Generated by Django 2.2.1 on 2019-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190626_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.CharField(default='Data/no_image.png', max_length=30),
        ),
    ]
