# Generated by Django 2.2.1 on 2019-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_place_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token',
            field=models.CharField(default='NoneUser', max_length=50),
        ),
    ]
