# Generated by Django 2.2.1 on 2019-07-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_appuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='info',
            field=models.CharField(default='NoneQuest', max_length=50),
        ),
    ]
