# Generated by Django 2.2.1 on 2019-07-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_quest_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(default='QuestName', max_length=20),
        ),
    ]
