# Generated by Django 2.2.1 on 2019-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_locationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(default='NonePlaceInfo'),
        ),
    ]
